version: '3.8'
services:
  angular-app:
    build: 
      context: .
      args:
        - API_URL=${API_URL}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
    container_name: docker_prueba
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
